name = "r2-divine-video"
main = "src/r2_proxy_worker.mjs"
compatibility_date = "2024-08-01"
account_id = "c84e7a9bf7ed99cb41b8e73566568c75"

# Production route for r2.divine.video
[[routes]]
pattern = "r2.divine.video/*"
zone_name = "divine.video"

# Staging route for r2-staging.divine.video
[[routes]]
pattern = "r2-staging.divine.video/*"
zone_name = "divine.video"