name = "cf-stream-service"
main = "src/worker.mjs"
compatibility_date = "2024-08-01"
account_id = "c84e7a9bf7ed99cb41b8e73566568c75"

# Default (used by wrangler dev without --env)
[vars]
LOOKUPS_ENABLED = true
# Stream removed - using R2 only
DEV_AUTH_MODE = "true"
STREAM_DOMAIN = "cdn.divine.video"
R2_PUBLIC_DOMAIN = "r2.divine.video"

[[kv_namespaces]]
binding = "MEDIA_KV"
# Create a KV and paste its id here: wrangler kv namespace create MEDIA_KV
id = "fc3fb1f988894752ae62462d5d0d2222"

# Staging environment
[env.staging]
name = "cf-stream-service-staging"
account_id = "c84e7a9bf7ed99cb41b8e73566568c75"
[env.staging.vars]
LOOKUPS_ENABLED = true
# Stream removed - using R2 only
DEV_AUTH_MODE = "true"
STREAM_DOMAIN = "cdn.divine.video"
R2_PUBLIC_DOMAIN = "r2-staging.divine.video"
[[env.staging.kv_namespaces]]
binding = "MEDIA_KV"
id = "eca883e0a5374b32ab92b3747235a1e3"

# Production environment
[env.production]
name = "cf-stream-service-prod"
account_id = "c84e7a9bf7ed99cb41b8e73566568c75"
routes = [
  { pattern = "blossom.divine.video/*", zone_name = "divine.video" }
]
[env.production.vars]
LOOKUPS_ENABLED = true
# Stream removed - using R2 only
CLOUDFLARE_ACCOUNT_ID = "c84e7a9bf7ed99cb41b8e73566568c75"
# Stream removed - R2 is primary storage
R2_ONLY_MODE = "true"
STREAM_DOMAIN = "cdn.divine.video"
R2_PUBLIC_DOMAIN = "r2.divine.video"
MODERATION_ENABLED = "true"  # Enable content moderation
[[env.production.kv_namespaces]]
binding = "MEDIA_KV"
id = "effcf271031647f0947983f5f4211aa2"
# Moderation KV for checking moderation results
[[env.production.kv_namespaces]]
binding = "MODERATION_KV"
id = "eee0689974834390acd39d543002cac3"

# R2 bucket binding for video migration
[[r2_buckets]]
binding = "R2_VIDEOS"
bucket_name = "nostrvine-media"

# Staging R2 bucket
[[env.staging.r2_buckets]]
binding = "R2_VIDEOS"
bucket_name = "nostrvine-media"

# Production R2 bucket
[[env.production.r2_buckets]]
binding = "R2_VIDEOS"
bucket_name = "nostrvine-media"

# Production Queue producer for video moderation
[[env.production.queues.producers]]
binding = "MODERATION_QUEUE"
queue = "video-moderation-queue"

# Secrets expected (set per environment with `wrangler secret put ... --env <name>`):
# - MIGRATION_ADMIN_TOKEN
# - MODERATION_ADMIN_TOKEN (for admin blocking endpoints)
