name = "blossom-sdk-worker"
main = "src/index.mjs"
compatibility_date = "2024-08-01"
account_id = "c84e7a9bf7ed99cb41b8e73566568c75"

# Default (used by wrangler dev without --env)
[vars]
DEV_AUTH_MODE = "true"
STREAM_DOMAIN = "cdn.divine.video"

[[kv_namespaces]]
binding = "MEDIA_KV"
id = "fc3fb1f988894752ae62462d5d0d2222"

# R2 bucket binding for blob storage
[[r2_buckets]]
binding = "R2_BLOBS"
bucket_name = "nostrvine-media"

# Staging environment
[env.staging]
name = "blossom-sdk-worker-staging"
account_id = "c84e7a9bf7ed99cb41b8e73566568c75"

[env.staging.vars]
DEV_AUTH_MODE = "true"
STREAM_DOMAIN = "cdn-staging.divine.video"

[[env.staging.kv_namespaces]]
binding = "MEDIA_KV"
id = "eca883e0a5374b32ab92b3747235a1e3"

[[env.staging.r2_buckets]]
binding = "R2_BLOBS"
bucket_name = "nostrvine-media"

# Production environment
[env.production]
name = "blossom-sdk-worker-prod"
account_id = "c84e7a9bf7ed99cb41b8e73566568c75"
routes = [
  { pattern = "blossom-sdk.divine.video/*", zone_name = "divine.video" }
]

[env.production.vars]
STREAM_DOMAIN = "cdn.divine.video"

[[env.production.kv_namespaces]]
binding = "MEDIA_KV"
id = "effcf271031647f0947983f5f4211aa2"

[[env.production.r2_buckets]]
binding = "R2_BLOBS"
bucket_name = "nostrvine-media"
